USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JobRole] (
	[JobRoleId]				[UNIQUEIDENTIFIER]	NOT NULL,
	[Name]					[nvarchar](100)		NOT NULL,		
	[IsActive]				[bit]				NOT NULL,

 CONSTRAINT [PK_JobRole] PRIMARY KEY CLUSTERED 
(
	[JobRoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO