USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Workflow] (
	[WorkflowId]			[UNIQUEIDENTIFIER]	NOT NULL,
	[WorkflowCategoryId]	[UNIQUEIDENTIFIER]	NOT NULL,
	[Name]					[NVARCHAR](100)		NOT NULL,	
	[Description]			[NVARCHAR](2000)	NOT NULL,
	[IsActive]				[BIT]				NOT NULL,

 CONSTRAINT [PK_Workflow] PRIMARY KEY CLUSTERED 
(
	[WorkflowId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE dbo.Workflow ADD CONSTRAINT
	FK_WorkFlow_WorkFlowCategory FOREIGN KEY
	(
		WorkflowCategoryId
	)
	REFERENCES dbo.WorkflowCategory
	(
		WorkflowCategoryId
	) 
	ON UPDATE  NO ACTION 
	ON DELETE  NO ACTION 

GO
