USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WorkflowNode] (
	[WorkflowNodeId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[WorkflowId]			[UNIQUEIDENTIFIER]	NOT NULL,
	[Name]					[NVARCHAR](100)		NOT NULL,	
	[Description]			[NVARCHAR](2000)	NOT NULL,
	[IsActive]				[BIT]				NOT NULL,

 CONSTRAINT [PK_WorkflowNode] PRIMARY KEY CLUSTERED 
(
	[WorkflowNodeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE dbo.WorkflowNode ADD CONSTRAINT
	FK_Workflow_WorkflowNode FOREIGN KEY
	(
		WorkflowId
	)
	REFERENCES dbo.Workflow
	(
		WorkflowId
	) 
	ON UPDATE  NO ACTION 
	ON DELETE  NO ACTION 

GO