USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ContactGroup](
	[ContactGroupId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[PreferredContactId]	[UNIQUEIDENTIFIER]	NULL,	
	[Notes]					[NVARCHAR](500)		NULL,	
	[IsActive]				[BIT]				NOT NULL,
 CONSTRAINT [PK_ContactGroup] PRIMARY KEY CLUSTERED 
(
	[ContactGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

GO

ALTER TABLE Contact
ADD  CONSTRAINT FK_Contact_ContactGroup 
	FOREIGN KEY
	(
		ContactGroupId
	)
	REFERENCES ContactGroup
	(
		ContactGroupId
	)
GO



