USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Asset](
	[AssetId]			[UNIQUEIDENTIFIER]	NOT NULL,
	[AssetTypeId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[Name]				[NVARCHAR](50)		NOT NULL,
	[BadgeNo]			[NVARCHAR](20) ]	NULL,
	[Description]		[NVARCHAR](2000)	NULL,
	[IsActive]			[bit]				NOT NULL,
 CONSTRAINT [PK_Asset] PRIMARY KEY CLUSTERED 
(
	[AssetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

GO

ALTER TABLE dbo.Asset ADD CONSTRAINT
	FK_Asset_AssetType FOREIGN KEY
	(
	AssetTypeId
	) REFERENCES dbo.AssetType
	(
	AssetTypeId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 

GO
