USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contact](
	[ContactId]			[UNIQUEIDENTIFIER]	NOT NULL,
	[ContactGroupId]	[UNIQUEIDENTIFIER]	NOT NULL,
	[ContactTypeId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[Value]				[NVARCHAR](250)		NOT NULL,	
	[IsActive]			[BIT]				NOT NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[ContactId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

GO

ALTER TABLE Contact
ADD  CONSTRAINT FK_Contact_ContactType
	FOREIGN KEY
	(
		ContactTypeId
	)
	REFERENCES ContactType 
	(
		ContactTypeId
	)
GO
