USE [CRM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WorkflowAction] (
	[WorkflowActionId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[WorkflowNodeId]		[UNIQUEIDENTIFIER]	NOT NULL,
	[Name]					[NVARCHAR](100)		NOT NULL,	
	[Description]			[NVARCHAR](2000)	NOT NULL,
	[DisplayOrder]			[INT]				NOT NULL,
	[IsActive]				[BIT]				NOT NULL,

 CONSTRAINT [PK_WorkflowAction] PRIMARY KEY CLUSTERED 
(
	[WorkflowActionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE dbo.WorkflowAction ADD CONSTRAINT
	FK_WorkflowAction_WorkflowNode FOREIGN KEY
	(
		WorkflowNodeId
	)
	REFERENCES dbo.WorkflowNode
	(
		WorkflowNodeId
	) 
	ON UPDATE  NO ACTION 
	ON DELETE  NO ACTION 

GO